<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Organizational Competency Profile</title>
    <style>
        @page {
  size: A4;
  @bottom-right {
    content: "Page " counter(page) " of " counter(pages);
  }
  @bottom-left {
    content: string(footerTitle);
  }
}
body {
            font-family: 'Inter', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #ffffff;
            font-size: 8px; /* Reduced font size */
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 10px;
            background-color: #ffffff;
            border-radius: 8px;
        }
        .header, .section-title {
            text-align: left;
            margin: 10px;
            padding: 9px;
        }
        .header h1, .section-title h2 {
            margin: 0;
            color:  #000035;
            font-size: 10px; /* Reduced font size */
        }
        .profile-section, .assessment-section {
            margin-bottom: 10px;
        }
        .profile-details, .qualification-list {
            margin-bottom: 5px;
        }
        .profile-details p, .qualification-item, .assessment-item {
            margin: 0;
            padding: 4px;


        }
        .profile-details strong, .qualification-item h3 {
            color:  #000035;
            font-size: 9px; /* Reduced font size */
        }

.footer {
  string-set: footerTitle content() width: 100%;
  float: left;
  height: 1em;
  padding-right: 0;
  font-size: 0.6em;
  padding-top: 0.4em;
}
.chart {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    align-items: center;
}
.chart img {
    max-width: 30%;
    margin: 10px;
}

        /* Additional CSS for other charts */
        .normal-chart img {
            max-width: 100%;
            margin: 20px 0;
        }
        .profile-details-table td{
            border-collapse: collapse;
            width: 100%
            border: 1px solid  #000035; /* Added border to table */

        }


.right-align {display: -webkit-box; display: -webkit-flex; display: flex; justify-content: flex-end; -webkit-justify-content: flex-end; text-align:right;}
    </style>
</head>
<body>
    <div class="container">

    <h1>Organizational Competency Profile</h1>

<div class="profile-section">
    <div class="profile-details">

        <table class="profile-details-table">
            <tr>
                <td><p><strong>Company Name:</strong></p></td>
                <td>Telecom Namibia</td>
            </tr>

                <td><p><strong>Country:</strong></p></td>
                <td>Windhoek</td>
            </tr>
            <tr>
                <td><p><strong>Phone Number:</strong></p></td>
                <td>+264 61 201 0000</td>
            </tr>
            <tr>
                <td><p><strong>Email:</strong></p></td>
                <td>skills@telecom.na</td>
            </tr>
            <tr>
                <td><p><strong>Website:</strong></p></td>
                <td>telecom.na</td>
            </tr>
        </table>
</div>
</div>


    <div>
        <div class="chart">
            <h3 class="section-title">Company Insights</h3>


            <img src="https://quickchart.io/chart?width=500&height=300&c={{ $ageUrl }}" alt="Age Chart"/>
            <img src="https://quickchart.io/chart?width=500&height=300&c={{ $genderUrl }}" alt="Gender Chart"/>
            <img src="https://quickchart.io/chart?width=500&height=300&c={{ $typeUrl }}" alt="Type Chart"/>
        </div>
        <div class="chart">
            <h3 class="section-title">Company Skill Audit Report</h3>

                <img src="https://quickchart.io/chart?width=500&height=300&c={{ $skillUrl }}"/>
        </div>

    </div>

      <div class="footer">
        Generated by SkillHarbor</a>
      </div>

    </div>

</body>
</html>
